<div class="byjoby-branding-non-free"><div class="byjoby-branding-non-free-wrapper">
    <h2>Non-free license. Sorry!</h2>
    <p>Unlike most of my experimental projects, the copyright of this page's original content is reserved by me or a client of mine.</p>
    <p>You're still free to dig into it to learn, obviously, and as always <a href="http://en.wikipedia.org/wiki/Fair_use">fair use</a> does apply. If you're really curious, you may also want to check the source code. While the design and content might be copyrighted, the code is often some sort of free license (I prefer MIT) or an amalgamation of existing free tools.</p>
</div></div>