<div class="byjobyfooter">
    More things by Joby:
    <ul>
        <li><a href="http://byjoby.com/" rel="me">byjoby.com</a></li>
        <li><a href="https://github.com/jobyone" rel="me">Github</a></li>
        <li><a href="http://codepen.io/jobyone/" rel="me">CodePen</a></li>
        <li><a href="https://plus.google.com/+JobyElliott" rel="me">Google+</a></li>
    </ul>
    <hr/>
    <p><strong>Software license:</strong> unless otherwise noted, original software posted to this site is <a href="/license.php">MIT Licensed</a>.</p>
    <hr/>
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Unless otherwise noted, <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">creative works on experimental.byjoby.com</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://experimental.byjoby.com" property="cc:attributionName" rel="cc:attributionURL">Joby Elliott</a> are licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-34822026-1', 'auto');
  ga('send', 'pageview');

</script>
